return
{
-- the app will look for the tracklength that is close

--{tracklength, shortname,  official asset name (look it up in assets.txt to get icons) }
{ 4224.0947, "Most",              "Autodrom Most - Grand Prix"},
{ 6191.8174, "Bathurst",          "Bathurst Circuit - Mount Panorama"},
{ 4171.6758 ,  "Bilster",           "Bilster Berg - Gesamtstrecke"},
{ 4202.6030 ,  "BilsterS",          "Bilster Berg - Gesamtstrecke Schikane"},
{ 2557.8333 ,  "BilsterOst",        "Bilster Berg - Ostschleife"},
{ 2574.8062 ,  "BilsterOstS",       "Bilster Berg - Ostschleife Schikane"},
{ 1653.0580 ,  "BilsterWest",       "Bilster Berg - Westschleife"},
{ 3934.6343 , "BrandsHatchGP",     "Brands Hatch Grand Prix - Grand Prix"},
{ 1939.5625 , "BrandsHatchIndy",   "Brands Hatch Indy - Indy"},
{ 5370.3188 , "Brno",              "Brno - Grand Prix"},
--{ ????.???? ,  "BrnoShort",         "Brno - Grand Prix (Short Pit Entry)"},
{ 3107.1226 ,  "ChangD",            "Chang International Circuit - D Circuit"},
{ 4538.9341 ,  "Chang",             "Chang International Circuit - Full Circuit"},
{ 4275.5996 , "Zandvoort",         "Circuit Zandvoort - Grand Prix"},
{ 2887.9404 , "ZandvoortNational", "Circuit Zandvoort - National"},
{ 2510.1907 , "ZandvoortClub",     "Circuit Zandvoort - Club"},
{ 3992.8501 , "Zolder",            "Circuit Zolder - Grand Prix"},
{ 4574.7422 , "LausitzDTMGP",      "DEKRA Lausitzring - DTM Grand Prix Course"},
{ 4536.0342 , "LausitzGP",         "DEKRA Lausitzring - Grand Prix Course"},
{ 3405.6841 , "LausitzShort",      "DEKRA Lausitzring - Short Course"},
{ 3434.4827 , "LausitzDTMShort",   "DEKRA Lausitzring - DTM Short Course"},
{ 5742.6631 , "DaytonaRoad",       "Daytona International Speedway - Road Course"},
--{ 4762.4058 ,  "DaytonaRoadMC",     "Daytona International Speedway - Road Course Motorcycle (2006)"},
--{ 4025.3291 ,  "DaytonaSpeedway",   "Daytona International Speedway - Speedway (Not Supported)"},
--{ ????.???? ,  "DubaiClub",         "Dubai Autodrome - Club Circuit"},
--{ ????.???? ,  "DubaiGP",           "Dubai Autodrome - Grand Prix Circuit"},
--{ ????.???? ,  "Dubai",             "Dubai Autodrome - International Circuit"},
--{ ????.???? ,  "DubaiNat",          "Dubai Autodrome - National Circuit"},
--{ ????.???? ,  "Falkenberg",        "Falkenberg Motorbana - Grand Prix"},
--{ ????.???? ,  "GelleråsenGP",      "Gelleråsen Arena - Grand Prix Circuit"},
--{ ????.???? ,  "GelleråsenShort",   "Gelleråsen Arena - Short Circuit"},
{ 4556.0313, "Hockenheim",        "Hockenheimring - Grand Prix"},
{ 3684.3120 , "HockenheimNational","Hockenheimring - National"},
{ 2585.4141 , "HockenheimShort",   "Hockenheimring - Short"},
{ 4359.0044 , "Hungaroring",       "Hungaroring - Grand Prix"},
{ 4897.3760 , "Imola",             "Imola - Grand Prix"},
{ 4069.3682 , "Indianapolis",      "Indianapolis 2012 - Grand Prix"},
{ 4193.3374 , "IndianapolisMoto",  "Indianapolis 2012 - Moto"},
--{ ????.???? ,  "Knutstorp",         "Knutstorp Ring - GP"},
{ 6113.2671 ,  "Macau",             "Macau - Grand Prix"},
--{ ????.???? ,  "MantorpLong",       "Mantorp Park - Long Circuit"},
--{ ????.???? ,  "MantorpShort",      "Mantorp Park - Short Circuit"},
{ 3807.9131 , "MidOhioChicane",    "Mid Ohio - Chicane"},
{ 3823.2102 , "MidOhioFull",       "Mid Ohio - Full"},
{ 2880.1135 , "MidOhioShort",      "Mid Ohio - Short"},
{ 5783.3403 , "Monza",             "Monza Circuit - Grand Prix"},
{ 2416.6360 , "MonzaJR",           "Monza Circuit - Junior"},
{ 3898.8025 , "Moscow",            "Moscow Raceway - FIM"},
{ 2512.9583 , "MoscowSprint",      "Moscow Raceway - Sprint"},
{ 3924.9500 , "MoscowFull",        "Moscow Raceway - Full"},
{ 4930.2803 , "AragónFast",        "Motorland Aragón - Fast Circuit"},
{ 5342.0801 , "AragónGP",          "Motorland Aragón - Grand Prix"},
{ 5073.2607 ,  "AragónMCGP",        "Motorland Aragón - Motorcycle Grand Prix"},
{ 2372.5940 ,  "AragónMCNat",       "Motorland Aragón - Motorcycle National"},
{ 2639.1780 ,  "AragónNat",         "Motorland Aragón - National"},
{ 3663.8022 , "Oschersleben",      "Motorsport Arena Oschersleben - A Course"},
{ 2397.6282 ,  "OscherslebenB",     "Motorsport Arena Oschersleben - B Course"},
{ 3646.6997 ,  "OscherslebenMCA",   "Motorsport Arena Oschersleben - Motorcycle A Course"},
{ 2381.0364 ,  "OscherslebenMCB",   "Motorsport Arena Oschersleben - Motorcycle B Course"},
--{ ????.???? ,  "Ningbo",            "Ningbo International Speedpark - Full circuit"},
--{ ????.???? ,  "NingboNoC",         "Ningbo International Speedpark - Full circuit no chicane"},
--{ ????.???? ,  "NingboInter",       "Ningbo International Speedpark - Intermediate circuit"},
--{ ????.???? ,  "NingboInterNoC",    "Ningbo International Speedpark - Intermediate circuit no chicane"},
--{ ????.???? ,  "NingboShort",       "Ningbo International Speedpark - Short circuit"},
{ 25361.5176 , "Nordschleife24",    "Nordschleife - 24 Hours"},
{ 20785.3945 , "Nordschleife",     "Nordschleife - Nordschleife"},
{ 20785.5781 ,  "NordschleifeTourist", "Nordschleife - Tourist"},
{ 24321.3066 , "NordschleifeVLN",  "Nordschleife - VLN"},
{ 2210.3872 , "Norisring",         "Norisring - Grand Prix"},
{ 5112.6201 , "NürburgringFast",   "Nürburgring - Grand Prix Fast Chicane"},
{ 3609.2053 , "NürburgringSprint", "Nürburgring - Sprint"},
{ 5123.2124 , "Nürburgring",       "Nürburgring - Grand Prix"},
{ 3596.4531 , "NürburgringShort",  "Nürburgring - Sprint Fast Chicane"},
{ 5787.7212 ,  "PaulRicard1A",      "Paul Ricard - Solution 1A"},
{ 5880.4438 ,  "PaulRicard1CV2",    "Paul Ricard - Solution 1C-V2"},
{ 3488.6926 ,  "PaulRicard2AS",     "Paul Ricard - Solution 2A short"},
{ 3859.9202 ,  "PaulRicard3C",      "Paul Ricard - Solution 3C"},
{ 3885.0781 , "PortimaoClub",      "Portimao Circuit - Club"},
{ 3880.8940 , "PortimaoChicane",   "Portimao Circuit - Club Chicane"},
{ 4623.4609 , "Portimao",          "Portimao Circuit - Grand Prix"},
{ 4148.3921 , "PortimaoNational",  "Portimao Circuit - National"},
{ 3797.2446 , "Raceroom",          "RaceRoom Raceway - Grand Prix"},
{ 3356.2039 , "RaceroomBridge",    "RaceRoom Raceway - Bridge"},
{ 3840.5679 , "RaceroomClassic",   "RaceRoom Raceway - Classic"},
{ 3628.0947 , "RaceroomClassicSprint","RaceRoom Raceway - Classic Sprint"},
{ 3604.7188 , "RaceroomNational",  "RaceRoom Raceway - National"},
{ 4305.5625 , "RedBullRing",       "Red Bull Ring Spielberg - Grand Prix Circuit"},
{ 2328.2979 ,  "RedBullRingNat",    "Red Bull Ring Spielberg - Südschleife National Circuit"},
--{ ????.???? ,  "RoadAmerica",       "Road America - Grand Prix"},
{ 3653.8242 , "Sachsenring",       "Sachsenring - Grand Prix"},
{ 4196.2661 ,  "Salzburgring",      "Salzburgring - Grand Prix"},
--{ ????.???? ,  "ScandinavianGP",    "Scandinavian Raceway - Grand Prix"},
--{ ????.???? ,  "ScandinavianSouth", "Scandinavian Raceway - South"},
{ 5528.1265 ,  "SepangGP",          "Sepang - Grand Prix"},
{ 2792.1316 ,  "SepangNorth",       "Sepang - North"},
{ 2603.6506 , "SepangSouth",       "Sepang - South"},
{ 5463.5103 , "ShanghaiGP",        "Shanghai Circuit - Grand Prix"},
{ 4614.6343 , "ShanghaiInter",     "Shanghai Circuit - Intermediate (WTCC)"},
{ 2968.9734 , "ShanghaiWest",      "Shanghai Circuit - West Long"},
--{ ????.???? ,  "SilverstoneGP",     "Silverstone Circuit - Grand Prix"},
--{ ????.???? ,  "SilverstoneHist",   "Silverstone Circuit - Historic Grand Prix"},
--{ ????.???? ,  "SilverstoneInter",  "Silverstone Circuit - International"},
--{ ????.???? ,  "SilverstoneNat",    "Silverstone Circuit - National"},
{ 5915.0332 , "Slovakia",          "Slovakia Ring - Grand Prix"},
{ 3208.6384 , "SonomaSprint",      "Sonoma Raceway - Sprint"},
{ 4101.1851 , "SonomaWTCC",        "Sonoma Raceway - WTCC"},
{ 3706.5615 , "SonomaIRL",         "Sonoma Raceway - IRL"},
{ 4046.4993 , "SonomaLong",        "Sonoma Raceway - Long"},
{ 6979.6763 , "SpaClassic",        "Spa-Francorchamps - Classic"},
{ 6979.7124 , "SpaComb",           "Spa-Francorchamps - Combined"},
{ 6979.6768 , "SpaGP",             "Spa-Francorchamps - Grand Prix"},
{ 1700.7498 , "StoweLong",         "Stowe Circuit - Long"},
{ 1257.9292 , "StoweShort",        "Stowe Circuit - Short"},
{ 2234.5293 , "SuzukaEast",        "Suzuka Circuit - East Course"},
{ 5801.7271 , "Suzuka",            "Suzuka Circuit - Grand Prix"},
{ 3464.6255 , "SuzukaWest",        "Suzuka Circuit - West Course"},
{ 3374.9426 , "MotegiEast",        "Twin Ring Motegi - East Course"},
{ 4744.9932 , "MotegiRoad",        "Twin Ring Motegi - Road Course"},
{ 1467.3462 , "MotegiWest",        "Twin Ring Motegi - West Course"},
--{ ????.???? ,  "Vålerbanen",        "Vålerbanen - Full Circuit"},
{ 5436.2158 , "WatkinsGlenGP",     "Watkins Glen International - Grand Prix"},
{ 5443.8296 , "WatkinsGlenGPi",    "Watkins Glen International - Grand Prix with Inner Loop"},
{ 3906.0850 , "WatkinsGlenS",      "Watkins Glen International - Short Circuit"},
{ 3922.8916 , "WatkinsGlenSi",     "Watkins Glen International - Short with Inner loop"},
{ 3585.5369 , "LagunaSeca",        "WeatherTech Raceway Laguna Seca - Grand Prix"},
--{ ????.???? ,  "ZhejiangEast",      "Zhejiang Circuit - East circuit"},
--{ ????.???? ,  "ZhejiangGP",        "Zhejiang Circuit - Grand Prix"},
{ 4305.7715, "ZhuhaiGP" ,          "Zhuhai Circuit - Grand Prix"},
}