return
{
-- layout ID
["7112"] = { track= "Autodrom Most",   layout="Grand Prix", short="GP"},
["1846"] = { track= "Bathurst Circuit",   layout="Mount Panorama", short="MP"},
["7819"] = { track= "Bilster Berg",   layout="Gesamtstrecke", short="G"},
["8069"] = { track= "Bilster Berg",   layout="Gesamtstrecke Schikane", short="GS"},
["8070"] = { track= "Bilster Berg",   layout="Ostschleife", short="O"},
["8071"] = { track= "Bilster Berg",   layout="Ostschleife Schikane", short="OS"},
["8095"] = { track= "Bilster Berg",   layout="Westschleife", short="W"},
["9473"] = { track= "Brands Hatch Grand Prix",   layout="Grand Prix", short="GP"},
["2520"] = { track= "Brands Hatch Indy",   layout="Indy", short="I"},
["5298"] = { track= "Brno",   layout="Grand Prix", short="GP"},
["9796"] = { track= "Brno",   layout="Grand Prix (Short Pit Entry)", short="GPSPE"},
["4944"] = { track= "Chang International Circuit",   layout="D Circuit", short="C"},
["4253"] = { track= "Chang International Circuit",   layout="Full Circuit", short="FC"},
["1679"] = { track= "Circuit Zandvoort 2019",   layout="Club", short="C"},
["1678"] = { track= "Circuit Zandvoort 2019",   layout="Grand Prix", short="GP"},
["1680"] = { track= "Circuit Zandvoort 2019",   layout="National", short="N"},
["1684"] = { track= "Circuit Zolder",   layout="Grand Prix", short="GP"},
["11908"] = { track= "Circuit de Charade",   layout="Classic Racing School", short="CRS"},
["10904"] = { track= "Circuit de Charade",   layout="Grand Prix", short="GP"},
["9055"] = { track= "DEKRA Lausitzring",   layout="DTM Grand Prix Course", short="DGPC"},
["2468"] = { track= "DEKRA Lausitzring",   layout="DTM Short Course", short="DSC"},
["10328"] = { track= "DEKRA Lausitzring",   layout="GP Course Oval T1", short="GCOT"},
["6166"] = { track= "DEKRA Lausitzring",   layout="Grand Prix Course", short="GPC"},
["3291"] = { track= "DEKRA Lausitzring",   layout="Short Course", short="SC"},
["8367"] = { track= "Daytona International Speedway",   layout="Road Course", short="RC"},
["8655"] = { track= "Daytona International Speedway",   layout="Road Course Motorcycle (2006)", short="RCM2"},
["8648"] = { track= "Daytona International Speedway",   layout="Speedway (Not Supported)", short="SNS"},
["10394"] = { track= "Donington Park",   layout="Grand Prix", short="GP"},
["10725"] = { track= "Donington Park",   layout="National", short="N"},
["7976"] = { track= "Dubai Autodrome",   layout="Club Circuit", short="CC"},
["6587"] = { track= "Dubai Autodrome",   layout="Grand Prix Circuit", short="GPC"},
["7978"] = { track= "Dubai Autodrome",   layout="International Circuit", short="IC"},
["7977"] = { track= "Dubai Autodrome",   layout="National Circuit", short="NC"},
["6140"] = { track= "Falkenberg Motorbana",   layout="Grand Prix", short="GP"},
["5925"] = { track= "Gelleråsen Arena",   layout="Grand Prix Circuit", short="GPC"},
["6138"] = { track= "Gelleråsen Arena",   layout="Short Circuit", short="SC"},
["1693"] = { track= "Hockenheimring",   layout="Grand Prix", short="GP"},
["1763"] = { track= "Hockenheimring",   layout="National", short="N"},
["1764"] = { track= "Hockenheimring",   layout="Short", short="S"},
["10274"] = { track= "Hockenheimring DMEC",   layout="DMEC", short="D"},
["1866"] = { track= "Hungaroring",   layout="Grand Prix", short="GP"},
["1850"] = { track= "Imola",   layout="Grand Prix", short="GP"},
["1852"] = { track= "Indianapolis 2012",   layout="Grand Prix", short="GP"},
["2014"] = { track= "Indianapolis 2012",   layout="Moto", short="M"},
["9957"] = { track= "Indianapolis Motor Speedway",   layout="Historic", short="H"},
["9958"] = { track= "Indianapolis Motor Speedway",   layout="Oval", short="O"},
["9943"] = { track= "Indianapolis Motor Speedway",   layout="Road Course", short="RC"},
["10463"] = { track= "Interlagos",   layout="Grand Prix", short="GP"},
["6137"] = { track= "Knutstorp Ring",   layout="GP", short="G"},
["1682"] = { track= "Lakeview Hillclimb",   layout="Full Run", short="FR"},
["2181"] = { track= "Lakeview Hillclimb",   layout="Reverse", short="R"},
["2123"] = { track= "Macau",   layout="Grand Prix", short="GP"},
["6010"] = { track= "Mantorp Park",   layout="Long Circuit", short="LC"},
["6167"] = { track= "Mantorp Park",   layout="Short Circuit", short="SC"},
["1676"] = { track= "Mid Ohio",   layout="Chicane", short="C"},
["1674"] = { track= "Mid Ohio",   layout="Full", short="F"},
["1675"] = { track= "Mid Ohio",   layout="Short", short="S"},
["1671"] = { track= "Monza Circuit",   layout="Grand Prix", short="GP"},
["1672"] = { track= "Monza Circuit",   layout="Junior", short="J"},
["3683"] = { track= "Moscow Raceway",   layout="FIM", short="F"},
["3383"] = { track= "Moscow Raceway",   layout="Full", short="F"},
["2473"] = { track= "Moscow Raceway",   layout="Sprint", short="S"},
["9043"] = { track= "Motorland Aragón",   layout="Fast Circuit", short="FC"},
["8704"] = { track= "Motorland Aragón",   layout="Grand Prix", short="GP"},
["9040"] = { track= "Motorland Aragón",   layout="Motorcycle Grand Prix", short="MGP"},
["9042"] = { track= "Motorland Aragón",   layout="Motorcycle National", short="MN"},
["9041"] = { track= "Motorland Aragón",   layout="National", short="N"},
["9483"] = { track= "Motorland Aragón",   layout="WTCR", short="W"},
["2384"] = { track= "Motorsport Arena Oschersleben",   layout="A Course", short="C"},
["7753"] = { track= "Motorsport Arena Oschersleben",   layout="B Course", short="C"},
["7754"] = { track= "Motorsport Arena Oschersleben",   layout="Motorcycle A Course", short="MC"},
["7755"] = { track= "Motorsport Arena Oschersleben",   layout="Motorcycle B Course", short="MC"},
["7273"] = { track= "Ningbo International Speedpark",   layout="Full circuit", short="Fc"},
["8309"] = { track= "Ningbo International Speedpark",   layout="Full circuit no chicane", short="Fcnc"},
["8310"] = { track= "Ningbo International Speedpark",   layout="Intermediate circuit", short="Ic"},
["8311"] = { track= "Ningbo International Speedpark",   layout="Intermediate circuit no chicane", short="Icnc"},
["8314"] = { track= "Ningbo International Speedpark",   layout="Short circuit", short="Sc"},
["10392"] = { track= "Nogaro Circuit Paul Armagnac",   layout="Caupenne Circuit", short="CC"},
["10258"] = { track= "Nogaro Circuit Paul Armagnac",   layout="Club Circuit", short="CC"},
["9659"] = { track= "Nogaro Circuit Paul Armagnac",   layout="Grand Prix Circuit", short="GPC"},
["5095"] = { track= "Nordschleife",   layout="24 Hours", short="2H"},
["2813"] = { track= "Nordschleife",   layout="Nordschleife", short="N"},
["5093"] = { track= "Nordschleife",   layout="Tourist", short="T"},
["4975"] = { track= "Nordschleife",   layout="VLN", short="V"},
["2518"] = { track= "Norisring",   layout="Grand Prix", short="GP"},
["1691"] = { track= "Nürburgring",   layout="Grand Prix", short="GP"},
["2010"] = { track= "Nürburgring",   layout="Grand Prix Fast Chicane", short="GPFC"},
["9847"] = { track= "Nürburgring",   layout="Müllenbachschleife", short="l"},
["3377"] = { track= "Nürburgring",   layout="Sprint", short="S"},
["2011"] = { track= "Nürburgring",   layout="Sprint Fast Chicane", short="SFC"},
["11909"] = { track= "Paul Ricard",   layout="Solution 1A", short="1A"},
["4246"] = { track= "Paul Ricard",   layout="Solution 1A-V2", short="1A2"},
["4247"] = { track= "Paul Ricard",   layout="Solution 1C-V2", short="1C2"},
["4248"] = { track= "Paul Ricard",   layout="Solution 2A short", short="2As"},
["2867"] = { track= "Paul Ricard",   layout="Solution 3C", short="3C"},
["1784"] = { track= "Portimao Circuit",   layout="Club", short="C"},
["1785"] = { track= "Portimao Circuit",   layout="Club Chicane", short="CC"},
["1778"] = { track= "Portimao Circuit",   layout="Grand Prix", short="GP"},
["1783"] = { track= "Portimao Circuit",   layout="National", short="N"},
["1709"] = { track= "RaceRoom Hillclimb",   layout="Full Run", short="FR"},
["2214"] = { track= "RaceRoom Hillclimb",   layout="Reverse", short="R"},
["266"] = { track= "RaceRoom Raceway",   layout="Bridge", short="B"},
["264"] = { track= "RaceRoom Raceway",   layout="Classic", short="C"},
["265"] = { track= "RaceRoom Raceway",   layout="Classic Sprint", short="CS"},
["263"] = { track= "RaceRoom Raceway",   layout="Grand Prix", short="GP"},
["267"] = { track= "RaceRoom Raceway",   layout="National", short="N"},
["2556"] = { track= "Red Bull Ring Spielberg",   layout="Grand Prix Circuit", short="GPC"},
["11296"] = { track= "Red Bull Ring Spielberg",   layout="Moto", short="M"},
["5794"] = { track= "Red Bull Ring Spielberg",   layout="Südschleife National Circuit", short="dNC"},
["5276"] = { track= "Road America",   layout="Grand Prix", short="GP"},
["3538"] = { track= "Sachsenring",   layout="Grand Prix", short="GP"},
["2026"] = { track= "Salzburgring",   layout="Grand Prix", short="GP"},
["5301"] = { track= "Scandinavian Raceway",   layout="Grand Prix", short="GP"},
["6164"] = { track= "Scandinavian Raceway",   layout="South", short="S"},
["6341"] = { track= "Sepang",   layout="Grand Prix", short="GP"},
["6578"] = { track= "Sepang",   layout="North", short="N"},
["6579"] = { track= "Sepang",   layout="South", short="S"},
["2027"] = { track= "Shanghai Circuit",   layout="Grand Prix", short="GP"},
["4041"] = { track= "Shanghai Circuit",   layout="Intermediate (WTCC)", short="IW"},
["4042"] = { track= "Shanghai Circuit",   layout="West Long", short="WL"},
["4039"] = { track= "Silverstone Circuit",   layout="Grand Prix", short="GP"},
["5862"] = { track= "Silverstone Circuit",   layout="Historic Grand Prix", short="HGP"},
["5816"] = { track= "Silverstone Circuit",   layout="International", short="I"},
["5817"] = { track= "Silverstone Circuit",   layout="National", short="N"},
["2064"] = { track= "Slovakia Ring",   layout="Grand Prix", short="GP"},
["3913"] = { track= "Sonoma Raceway",   layout="IRL", short="I"},
["3912"] = { track= "Sonoma Raceway",   layout="Long", short="L"},
["2016"] = { track= "Sonoma Raceway",   layout="Sprint", short="S"},
["1854"] = { track= "Sonoma Raceway",   layout="WTCC", short="W"},
["4542"] = { track= "Spa-Francorchamps",   layout="Classic", short="C"},
["4543"] = { track= "Spa-Francorchamps",   layout="Combined", short="Co"},
["3870"] = { track= "Spa-Francorchamps",   layout="Grand Prix", short="GP"},
["6055"] = { track= "Stowe Circuit",   layout="Long", short="L"},
["6056"] = { track= "Stowe Circuit",   layout="Short", short="S"},
["2012"] = { track= "Suzuka Circuit",   layout="East Course", short="EC"},
["1841"] = { track= "Suzuka Circuit",   layout="Grand Prix", short="GP"},
["2013"] = { track= "Suzuka Circuit",   layout="West Course", short="WC"},
["9985"] = { track= "TT Circuit Assen",   layout="Grand Prix", short="GP"},
["10355"] = { track= "TT Circuit Assen",   layout="Motorcycle Course", short="MC"},
["10351"] = { track= "TT Circuit Assen",   layout="North Course", short="NC"},
["7027"] = { track= "Twin Ring Motegi",   layout="East Course", short="EC"},
["6658"] = { track= "Twin Ring Motegi",   layout="Road Course", short="RC"},
["7026"] = { track= "Twin Ring Motegi",   layout="West Course", short="WC"},
["9465"] = { track= "Vålerbanen",   layout="Full Circuit", short="FC"},
["9344"] = { track= "Watkins Glen International",   layout="Grand Prix", short="GP"},
["9324"] = { track= "Watkins Glen International",   layout="Grand Prix with Inner Loop", short="GPwIL"},
["9343"] = { track= "Watkins Glen International",   layout="Short Circuit", short="SC"},
["9177"] = { track= "Watkins Glen International",   layout="Short with Inner loop", short="SwIl"},
["1856"] = { track= "WeatherTech Raceway Laguna Seca",   layout="Grand Prix", short="GP"},
["8327"] = { track= "Zhejiang Circuit",   layout="East circuit", short="Ec"},
["8075"] = { track= "Zhejiang Circuit",   layout="Grand Prix", short="GP"},
["3464"] = { track= "Zhuhai Circuit",   layout="Grand Prix", short="GP"},
}